### ISSUE TITLE
Canonical list of IRB keyboard shortcuts?

### ISSUE THREAD

**Issue by stevecondylios** [ruby/irb#322]
I was shown by a friend the very nifty shortcut <kbd>ctrl</kbd> + <kbd>u</kbd> to cut the current line (followed by <kbd>ctrl</kbd> + <kbd>y</kbd> to paste). 

Is there a canonical list of the keyboard shortcuts available in IRB available somewhere? (It would be very helpful to view a list of such shortcuts so as to make full use of them.)

I found some resources linked to [here](https://stackoverflow.com/q/13094191/5783745), but I can't spot a definitive list of keyboard shortcuts anywhere. It would be awesome to make one if it doesn't exist somewhere already. It could be an `.md` file perhaps. But I am not sure where to find all the shortcuts if not already listed in text, perhaps in the IRB source code, but again I am not sure where. Happy to pilfer through to find them if that could be useful. If anyone has pointers on where to start it would be great to know.

**Comment by aycabta** [comment]
Many interactive environments on the shell use GNU Readline, as does IRB. If you want a list, [search for "readline cheat sheet"](https://www.google.com/search?q=Readline+cheat+sheet). It is also possible to customize it by "~/.inputrc", but you can find a lot of information by search engine too.

The same is true for other software that uses the GNU Readline, such as the RDBMS interactive environment, and the shell itself (Bash, and others).

In fact, some of them implement GNU Readline compatible features on their own. Reline reads ~/.inputrc as is, while zle reads ~/.zshrc.

Since this topic is not directly related to IRB, I'll close it for now.
