### ISSUE TITLE
In macOS, home and end keys no longer work

### ISSUE THREAD

**Issue by jkwuc89** [ruby/irb#330]
## Description
In macOS (I am using Monterey 12.1), the home and end keys no longer move the cursor to the start of the line and the end of the line respectively. Instead, these keys output the escape sequences you see in the screenshot below.

<img width="289" alt="Screen Shot 2022-01-12 at 6 28 57 AM" src="https://user-images.githubusercontent.com/1555064/149132121-88248c64-6d13-4efb-a576-14e8ac9c9234.png">

This behavior is new in irb that ships with Ruby 3.1. In the previous version, these keys worked as expected.

## Result of irb_info

```
Ruby version: 3.1.0
IRB version: irb 1.4.1 (2021-12-25)
InputMethod: ReidlineInputMethod with Reline 0.3.1
RUBY_PLATFORM: x86_64-darwin21
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator
I am using iTerm2 Build 3.4.14 which is configured to use `xterm-256color`.

## Setting Files
I am not using a settings file.

**Comment by jkwuc89** [comment]
I tested this using macOS's terminal app and the home and end keys also do not work there. I also retested `irb` under Ruby 3.0.3 to double-check that the home and end keys work properly which they do.

**Comment by jkwuc89** [comment]
I also tested this in a terminal on Ubuntu 20.04.3 LTS and the issue does not occur there.

**Comment by jkwuc89** [comment]
I managed to fix this by mapping Home and End keys in my iTerm2 profile key mappings to the hex codes 0x01 and 0x05 respectively. These hex codes map to Ctrl+A and Ctrl+E which in an iTerm2 session, function as Home (go to beginning of line) and End (go to end of line) and work as expected in irb. From my profile key mapping settings:

<img width="410" alt="Screen Shot 2022-01-12 at 10 09 16 AM" src="https://user-images.githubusercontent.com/1555064/149167501-325731bc-0d7e-49d4-9405-771c7c7d66c5.png">

**Comment by aycabta** [comment]
Would you try to run the following command and press Home/End key? You can exit with Ctrl+c.

```
ruby -r reline -e 'while (c = Reline::IOGate.getc); pp c; end'
```

Please copy the result.

**Comment by jkwuc89** [comment]
> ruby -r reline -e 'while (c = Reline::IOGate.getc); pp c; end'

```
❯ ruby -r reline -e 'while (c = Reline::IOGate.getc); pp c; end'
1
5
```

**Comment by jkwuc89** [comment]
I am seeing a similar issue with the Delete key. Output inside irb:
<img width="285" alt="Screen Shot 2022-01-24 at 6 43 30 AM" src="https://user-images.githubusercontent.com/1555064/150777091-1773bcd7-6643-4bd7-972f-9f39e1b08be4.png">

`ruby -r reline -e 'while (c = Reline::IOGate.getc); pp c; end'` shows the following for the Delete key.
```
❯ ruby -r reline -e 'while (c = Reline::IOGate.getc); pp c; end'
27
91
51
126
```

**Comment by sshock** [comment]
I am having the same problem with Home, End, and Delete keys and it is a major pain point for me.

Here's the output from `ruby -r reline -e 'while (c = Reline::IOGate.getc); pp c; end'` for each of these:

(Home):
```
27
91
72
```

(End):
```
27
91
70
```

(Delete):
```
27
91
51
126
```

(I believe @jkwuc89 's response for Home and End were flawed and resulted in just a 1 and a 5 because he had already re-mapped those to Ctrl+A and Ctrl+E).

Here are some more problematic keys that cause weird things to show up:

(Insert on Mac):
```
239
157
134
```

(Insert on PC):
```
27
91
50
126
```

(PgUp on Mac and PC):
```
27
91
53
126
```

(PgDn on Mac and PC):
```
27
91
54
126
```

**Comment by sshock** [comment]
I think this is a problem in reline, introduced in reline v0.2.7.

I switched to Ruby 3.0 with reline 0.2.0 and the problem went away.  Then I tried various versions of reline and the problem first shows up in reline 0.2.7.

**Comment by sshock** [comment]
I added this line to the `set_default_key_bindings_terminfo` method in `Reline::ANSI`:

```ruby
puts "MAPPING #{key.inspect} TO #{func}"
```

and it produced this:
```
MAPPING [27, 79, 72] TO ed_move_to_beg
MAPPING [27, 79, 70] TO ed_move_to_end
MAPPING [27, 79, 65] TO ed_prev_history
MAPPING [27, 79, 66] TO ed_next_history
MAPPING [27, 79, 67] TO ed_next_char
MAPPING [27, 79, 68] TO ed_prev_char
MAPPING [27, 91, 65] TO ed_prev_history
MAPPING [27, 91, 66] TO ed_next_history
MAPPING [27, 91, 67] TO ed_next_char
MAPPING [27, 91, 68] TO ed_prev_char
```

Those codes for Home and End don't match what's actually getting sent.  But how could the term info be wrong?  All other apps including bash and vim and you name it work totally fine in iTerm2, so I don't understand.

Also, it appears reline didn't even attempt to map the delete key...

**Comment by jitingcn** [comment]
> I think this may be a problem in reline, introduced in reline v0.2.7.
> 
> I switched to Ruby 3.0 with reline 0.2.0 and the problem went away. Then I tried various versions of reline and the problem first shows up in reline 0.2.7.
> 
> Digging further, it appears that the problem surfaced when default key bindings started using `set_default_key_bindings_terminfo` instead of `set_default_key_bindings_comprehensive_list`.

I have this problem too, and I have tried to test with different versions of reline by your inspiration, and I found [reline 0.2.6 74a7ffaa2fb0a48f5c790ac917489130fcf2bbde](https://github.com/ruby/reline/commit/74a7ffaa2fb0a48f5c790ac917489130fcf2bbde) is the first version have this problem.
I'm using Arch Linux with zsh.

**Comment by sshock** [comment]
Trying to understand terminfo I looked at the output of `infocmp xterm-256color -1 | grep home` and noticed `khome` and `home`:

```
        home=\E[H,
        khome=\EOH,
```

`khome` aka `key_home` == This is what should be received (input) when the home key is pressed

`home` aka `cursor_home` == This is what could be sent (output) to a terminal to tell it to move the cursor to the home position (very top left)

These are two very different things.

Now looking at the mapping in `set_default_key_bindings_terminfo`, it actually looks correct.  It is mapping key_home == "\EOH" == [27, 79, 72] to `:ed_move_to_beg`.

Which means the part that is wrong is actually on the input side of things.  `Reline::IOGate.getc` is getting a [27, 91, 72] == "\E[H" == cursor_home when I press the home key.

Which I think means either iTerm2 is sending the wrong thing or somehow it is getting changed to the wrong somewhere along the way before `Reline::IOGate.getc` gets it.

**Comment by sshock** [comment]
I did a bunch of testing and, although I have no idea how `vim` and other tools work fine, I am convinced that iTerm2 is sending the wrong escape sequence for Home and End (and Insert).

And as for Delete, PgUp, and PgDown, iTerm2 is sending correct codes for those, but Reline is not mapping them to anything.

So here are all the issues and solutions!

**Home key (khome)**
* Problem: iTerm2 maps it to `\E[H`, which is incorrect for xterm
* Solution: Change iTerm2 Key Mappings to map it to `\EOH`

**End key (kend)**
* Problem: iTerm2 maps it to `\E[F`, which is incorrect for xterm
* Solution: Change iTerm2 Key Mappings to map it to `\EOF`

**Delete key (kdch1 )**
* Problem: Reline doesn't map it to anything  (although somehow it works on linux)
* Solution: Update Reline code to map `'kdch1'` to `:key_delete`

**Insert key (kich1)**
* Problem 1: iTerm2 maps it to codes [239, 157, 134], which is incorrect for xterm
* Problem 2: Reline doesn't map it to anything
* Solution 1: Change iTerm2 Key Mappings to map it to `\E[2~`
* Solution 2: Update Reline code to map `'kich1'` to `:ed_ignore`

**PgUp key (kpp)**
* Problem: Reline doesn't map it to anything
* Solution: Update Reline code to map `'kpp'` to `:ed_ignore`

**PgDn key (knp)**
* Problem: Reline doesn't map it to anything
* Solution: Update Reline code to map `'knp'` to `:ed_ignore`

Here's a screenshot showing where Home, End, and Insert keys are fixed in iTerm2 to send the correct codes:

![iterm2 fixes](https://user-images.githubusercontent.com/1693761/156911727-ce0a25fd-51e6-4752-9ae4-6d5ee8a13eb6.png)

Here's a screenshot showing how to fix the Delete key in Reline, and also how to prevent Insert, PgUp, and PgDn from printing out nasties:

![reline fixes](https://user-images.githubusercontent.com/1693761/156912381-78e2f6a9-9792-4062-b8ca-4b0fea7a0393.png)

**Comment by aleksandrs-ledovskis** [comment]
Great investigation @sshock!

For those that are impatient till [reline#434](https://github.com/ruby/reline/pull/434) and [reline#433](https://github.com/ruby/reline/pull/433) lands and makes it upstream to "irb". The quick & dirty fix for local installation is to apply patches against "ansi.rb" file (located at `/<installation path to CRuby>/lib/ruby/3.1.0/reline/ansi.rb`).

- https://github.com/ruby/reline/commit/6b9babfbb687926b25c1f7197e639b902666e09e.patch
- https://github.com/ruby/reline/commit/a022af7abb48f62ff1e93e1dbf5ef4ba76cd06c3.patch

**Comment by BrianHawley** [comment]
For those who would prefer to do the above patches at runtime, for macOS/iTerm2, add this code to "~/.irbrc":
```ruby
require "reline/ansi"

# Fix insert, delete, pgup, and pgdown.
Reline::ANSI::CAPNAME_KEY_BINDINGS.merge!({
  'kich1' => :ed_ignore,
  'kdch1' => :key_delete,
  'kpp' => :ed_ignore,
  'knp' => :ed_ignore
})

Reline::ANSI.singleton_class.prepend(
  Module.new do
    def set_default_key_bindings(config)
      # Fix home and end.
      set_default_key_bindings_comprehensive_list(config)
      # Fix iTerm2 insert.
      key = [239, 157, 134]
      func = :ed_ignore
      config.add_default_key_binding_by_keymap(:emacs, key, func)
      config.add_default_key_binding_by_keymap(:vi_insert, key, func)
      config.add_default_key_binding_by_keymap(:vi_command, key, func)
      # The rest of the behavior.
      super
    end
  end
)
```
No switch to application mode needed, and no iTerm2 rebinding.

**Comment by sshock** [comment]
Does anyone know if aycabta is ok?  The irb and reline repos seem to be almost completely frozen without him.

**Comment by sshock** [comment]
I discovered a new workaround that is relatively simple and fixes all keys; just modify `~/.inputrc` to contain the following:
```
$if Ruby
    "\e[H": beginning-of-line
    "\e[F": end-of-line
    "\e[3~": delete-char
    "\e[2~": ""
    "\e[5~": ""
    "\e[6~": ""
    "\xef\x9d\x86": ""
$endif
```

**Comment by neonn** [comment]
Apologies for adding a (potentially) meaningless comment to this thread, but @BrianHawley 's fix seems to work for me. It's resolved a long-standing issue with `irb` - I'm using Arch Linux, but I've triple-checked my system config (`/etc/inputrc` etc.) compared to Ubuntu, and couldn't see a difference in the terminal's behaviour. Home/End/Delete etc. didn't work for me, even before `reline` 0.2.0, and hasn't worked since Ruby 2.6, when I started learning Ruby.

**Comment by sshock** [comment]
@neonn I think adding your experience is helpful and a good reminder to the maintainers of irb and reline that we still have people needing this to be fixed.

I've been waiting patiently for these fixes to be merged in (the last one is still DRAFT, but the first two are tiny and have been ready to go for _9 months_):
* https://github.com/ruby/reline/pull/433
* https://github.com/ruby/reline/pull/434
* https://github.com/ruby/reline/pull/462

**Comment by rgaufman** [comment]
The workarounds work, but any permanent solution?

**Comment by sshock** [comment]
> The workarounds work, but any permanent solution?

@rgaufman the [delete key is fixed](https://github.com/ruby/reline/pull/434) now, but we need one of these (preferably both) across the finish line to fix Home and End:
* https://github.com/ruby/reline/pull/433
* https://github.com/ruby/reline/pull/462

**Comment by kendofriendo** [comment]
> I discovered the following workaround for my setup (using archlinux, kitty and fish): `IRB.conf[:USE_MULTILINE] = false` in `~/.irbrc`

That also breaks command completion suggestions though while BrianHawley's solution doesn't.
