### ISSUE TITLE
Cannot save to history file in nomultiline mode with concurrent irb session

### ISSUE THREAD

**Issue by tompng** [ruby/irb#510]
## Description

When I use `irb --nomultiline` concurrently and enter `exit` in each irb session, irb raises error

```
[tomoya:irb]% bin/console --nomultiline
irb(main):001:0> `bin/console`.size
exit
=> 599
irb(main):002:0> exit
/path/to/irb/lib/irb/ext/save-history.rb:107:in `[]': no implicit conversion of Range into Integer (TypeError)

          history = history[@loaded_history_lines..-1] if @loaded_history_lines
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
	from /path/to/irb/lib/irb/ext/save-history.rb:107:in `save_history'
	from /path/to/irb/lib/irb/ext/save-history.rb:55:in `block in extended'
	from /path/to/irb/lib/irb.rb:499:in `block in run'
	from /path/to/irb/lib/irb.rb:499:in `each'
	from /path/to/irb/lib/irb.rb:499:in `run'
	from /path/to/irb/lib/irb.rb:416:in `start'
	from bin/console:6:in `<main>'
```

## Result of irb_info

```
irb(main):001:0> irb_info
=> 
Ruby version: 3.2.0
IRB version: irb 1.6.2 (2022-12-13)
InputMethod: RelineInputMethod with Reline 0.3.2
RUBY_PLATFORM: x86_64-darwin20
LANG env: ja_JP.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

Terminal.app

## Setting Files

> Are you using `~/.irbrc` and `~/.inputrc`?

No

**Comment by mthurman** [comment]
We've run into this too and it seems like this is because `Reline::HISTORY` inherits from `Array` and thus can deal with ranges: https://github.com/ruby/reline/blob/master/lib/reline/history.rb#L15-L18 but I don't think the C version can: https://github.com/ruby/readline-ext/blob/master/ext/readline/readline.c#L1712-L1729.

**Comment by chadrschroeder** [comment]
We're seeing this, too.  To recreate the issue:

1. Use the `--nomultiline` option (or `IRB.conf[:USE_MULTILINE] = false`).
2. In console 1, start IRB.
3. In console 2, start IRB.
4. In console 1, exit IRB.  This will exit cleanly.
5. In console 2, exit IRB.  This will crash on the error noted in the issue description.

[This commit](https://github.com/ruby/irb/commit/041ef53845a4b791993813472f76a63bcc7b3a19) is what introduced the problem.

As @mthurman pointed out, the issue is with `Reline::HISTORY`.  [These are the public instance methods for `Reline::HISTORY`](https://docs.ruby-lang.org/en/master/Reline/History.html).  The interface is pretty limited and the `[]` method can't accept a range.

So we can't do this:

```ruby
# irb/ext/save-history.rb
if File.exist?(history_file) &&
   File.mtime(history_file) != @loaded_history_mtime
  history = history[@loaded_history_lines..-1] if @loaded_history_lines
  append_history = true
end
```

One way to fix the issue would be something like this instead:

```ruby
# irb/ext/save-history.rb
if File.exist?(history_file) &&
   File.mtime(history_file) != @loaded_history_mtime
  @loaded_history_lines.times { history.delete_at(0) }
  append_history = true
end
```

That will work with `:USE_MULTILINE` set to `true` or `false`.
