### ISSUE TITLE
Emoji cause incorrect cursor position

### ISSUE THREAD

**Issue by will** [ruby/irb#622]
## Description

If there are emoji in the start of a line, the cursor appears to lag the actual insertion position, and it gets worse the more emoji there are. 

I originally suspected something wrong with my terminal emulator, however Pry in the same terminal works as expected, so now I think it's something with irb (or maybe reline?).

I've made a video:

https://github.com/ruby/irb/assets/1973/afd7d700-06fa-4489-9e1e-71cde2119b3e

## Result of irb_info

```
irb(main):001:0> irb_info
=>
Ruby version: 3.2.2
IRB version: irb 1.7.0 (2023-06-03)
InputMethod: RelineInputMethod with Reline 0.3.5
RUBY_PLATFORM: arm64-darwin22
LANG env: en_US.UTF-8
East Asian Ambiguous Width: 1
```

## Terminal Emulator

macos iterm2 Build 3.5.0beta10

## Setting Files

```
❯ file .irbrc .inputrc
.irbrc:   cannot open `.irbrc' (No such file or directory)
.inputrc: cannot open `.inputrc' (No such file or directory)
```

**Comment by tompng** [comment]
Thank you for reporting.
For Pry, it looks working when just pasting character but does not work for delete, insert,  and other text edit operation.
Also, bash have the same problem. sh and zsh avoids it by escaping it to `⚠<fe0f>` but have same problem for flags emoji.

I checked iTerm2 beta. Looks like the behavior depends on preference added in beta7:
`Preferences > Advanced > Experimental Features > Support variation selector 16 making emoji fullwidth outside of alternate screen mode?`
And there are similar preference for flag emoji added in beta9:
`Preferences > Advanced > Experimental Features > Flag emoji render full-width`

Workaround is to set these value to NO.

We cannot change Reline's behavior now because it will cause problem in other terminal emulators. I think it's not a bug of IRB or Reline but maybe a problem of iTerm2 beta that turns setting that have trade-offs ON by default.

**Comment by will** [comment]
Thanks for figuring it out @tompng! I noticed because I had that character in the IRB prompt when in production. I'll switch it to `⚠` or something else that works everywhere for now. 

I'll close this since it's not a irb/reline problem.
