### ISSUE TITLE
--inf-ruby-mode semantics

### ISSUE THREAD

**Issue by dgutov** [ruby/irb#68]
Can we make it imply `--nosingleline` and `--nomultiline`, but not anything else?

In particular, we (the inf-ruby upstream) decided not to use it because it also disables continuation prompts. Currently `inf-ruby` uses `--prompt default --noreadline` instead.

But with newer features here that we can't use from Emacs, it would be helpful if `--inf-ruby-mode` was an option one could use to avoid version checks. In particular, if `irb --inf-ruby-mode --prompt default` was a valid usage in the new IRB.

**Comment by dgutov** [comment]
About cares about Emacs support here?

**Comment by mkaschenko** [comment]
+1

**Comment by gcentauri** [comment]
i know its been 2 years since this opened, but i'd like to give it a +1.

maybe it has been addressed in newer versions of ruby, but at least with my local version of ruby 2.7.5, adding it to the command options causes irb to fail to return the next prompt until i type another newline. it seems like the `--noreadline` option is possibly causing an issue.

it *does* seem to work on Ruby 3 though, but for the Emacs integration it would be quite nice to depend on this flag as @dgutov suggests.

**Comment by gcentauri** [comment]
ah i see my particular issue was addressed here https://github.com/ruby/irb/issues/127

fwiw, i'm interested in helping with further Emacs support if any effort goes this way
