### ISSUE TITLE
`--tracer` flag (and extension) broken with recent versions of `tracer`

### ISSUE THREAD

**Issue by adam12** [ruby/irb#694]
## Description

The `--tracer` flag breaks `irb` when used with `0.2.2` version of `tracer`. I believe this was slightly hinted at in #630.

It works when requiring `tracer`, whereas `show_cmds` is extended with tracing options.

## Result of irb_info

```
irb(main):001> irb_info
Ruby version: 3.2.1
IRB version: irb 1.7.4 (2023-07-15)
InputMethod: RelineInputMethod with Reline 0.3.7
RUBY_PLATFORM: arm64-darwin22
LANG env: en_CA.UTF-8
East Asian Ambiguous Width: 1
```

**Comment by st0012** [comment]
@adam12 Yeah sorry I updated the tracer but didn't update the extension in IRB as I expected no one would use it due to lack of update on both sides.

Given that IRB's tracer extension hasn't received updated for many years, so I'd like to make it actually helpful in addition to fixing it for the new tracer. Would you mind sharing your use case of/expectation for it?

**Comment by adam12** [comment]
Should we disable the broken version temporarily? I actually don't know how useful the `--tracer` command line argument is, to be honest. It was just something I noticed while working on something else.

Ideally, it would function similar to `irb/debug`, where the commands are registered but are mostly stubs, where the `tracer` library is required upon first call or warned if unable to load.
