### ISSUE TITLE
Ctrl-D behaviour is different between normal IRB and irb:rdbg sessions

### ISSUE THREAD

**Issue by st0012** [ruby/irb#921]
## Description

In normal IRB sessions, ctrl-D is the same as `exit`, which exits the current IRB session. In `irb:rdbg` sessions, ctrl-D is executed by `debug`, which is the same as its `quit` command and will leave the entire process.

So in the a process that has multiple breakpoints, ctrl-D is semantically similar to `continue`. But once `irb:rdbg` is activated, ctrl-D's behaviour changes. This adds cognitive load to users as they need to be aware of the type of sessions they're in to perform the intended action.

**Comment by st0012** [comment]
I can't reproduce this issue anymore. Closing

**Comment by Aethelflaed** [comment]
I'm actually having issues with the `debug` gem because of the change of `EOF` handling, if I accept the offer to quit rdbg it "stalls" my rails server (not receiving new connections, unresponsive to ctrl-c, ..)

Shall I go to `debug` issues or do you think this may be related to what you describe here?
